# Generated by Django 4.2.13 on 2024-06-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postulacion',
            fields=[
                ('rut', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('pnombre', models.CharField(max_length=50)),
                ('appaterno', models.CharField(max_length=50)),
                ('apmaterno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('celular', models.IntegerField()),
                ('especializacion', models.CharField(max_length=50)),
                ('motivo', models.TextField()),
                ('id_genero', models.ForeignKey(db_column='idGenero', on_delete=django.db.models.deletion.CASCADE, to='app.genero')),
            ],
        ),
    ]
