# Generated by Django 4.2.13 on 2024-06-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_postulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='rut',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
