# Generated by Django 4.2.13 on 2024-06-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_postulacion_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='id_genero',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='tipo_genero',
            field=models.IntegerField(choices=[[0, 'Seleccione'], [1, 'Femenino'], [2, 'Masculino'], [3, '39 tipos de gay']], default=1),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id_genero',
            field=models.IntegerField(choices=[[0, 'Seleccione'], [1, 'Femenino'], [2, 'Masculino'], [3, '39 tipos de gay']]),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
