# Generated by Django 4.2.13 on 2024-06-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_postulacion_id_genero_postulacion_tipo_genero_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='tipo_genero',
            field=models.IntegerField(choices=[[0, 'Seleccione'], [1, 'Femenino'], [2, 'Masculino'], [3, '39 tipos de gay']], default=0),
        ),
    ]
