# Generated by Django 4.2.13 on 2024-06-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_alumno_alter_postulacion_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='tipo_genero',
            field=models.IntegerField(choices=[[0, 'Seleccione'], [1, 'Femenino'], [2, 'Masculino'], [3, 'Helicoptera']], default=0),
        ),
    ]
