# Generated by Django 5.0.6 on 2024-06-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_postulacion_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='atencion',
            fields=[
                ('id_atencion', models.AutoField(db_column='id_atencion', primary_key=True, serialize=False)),
                ('nom_mecanico', models.CharField(max_length=50)),
                ('nom_cliente', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('fecha_atencion', models.DateField()),
                ('categoria', models.IntegerField(choices=[(0, 'Seleccione'), (1, 'Mantención'), (2, 'Cambio de pieza'), (3, 'Limpieza')], default=0)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
