# Generated by Django 5.0.6 on 2024-06-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_atencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria_prod', models.IntegerField(choices=[(0, 'Seleccione'), (1, 'Ruedas'), (2, 'Suspensiones'), (3, 'Turbos'), (4, 'Frenos')], default=0)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='productos/')),
            ],
        ),
    ]
