# Generated by Django 4.2.13 on 2024-06-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='categoria',
            field=models.IntegerField(choices=[[0, 'Seleccione'], [1, 'Mantención'], [2, 'Cambio de pieza'], [3, 'Limpieza']], default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria_prod',
            field=models.IntegerField(choices=[[0, 'Seleccione'], [1, 'Ruedas'], [2, 'Suspensiones'], [3, 'Turbos'], [4, 'Frenos']], default=0),
        ),
    ]
